theme: jekyll-theme-hacker
title: 0xn0b174
description: Personal blog of 0xn0b174
author:
  name: 0xn0b174
  email: 0xn0b174@example.com
baseurl: ""
url: "https://0xn0b174.github.io"
plugins:
  - jekyll-feed
#logo: /assets/img/headshot_circle.png
#show_downloads: true